CREATE TABLE IF NOT EXISTS schema_versions(version integer PRIMARY KEY, applied_at timestamptz DEFAULT now());
INSERT INTO schema_versions(version) VALUES (2) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS controls(id integer PRIMARY KEY CHECK(id=1), running boolean NOT NULL DEFAULT false, updated_at timestamptz DEFAULT now());
INSERT INTO controls(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS workers(worker_id text PRIMARY KEY, stage text NOT NULL, heartbeat timestamptz, status text NOT NULL DEFAULT 'Not started');
INSERT INTO workers VALUES ('A','Materials',NULL,'Not started'),('B','Production',NULL,'Not started'),('C','Quality',NULL,'Not started') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS faults(worker_id text PRIMARY KEY REFERENCES workers, mode text NOT NULL DEFAULT 'NORMAL' CHECK(mode IN ('NORMAL','SLOW QUERY','LOCK TIMEOUT','CONSTRAINT VIOLATION')));
INSERT INTO faults(worker_id) SELECT worker_id FROM workers ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS fault_audit(id bigserial PRIMARY KEY, timestamp timestamptz DEFAULT now(), worker_id text, action text NOT NULL);
CREATE TABLE IF NOT EXISTS orders(order_id uuid PRIMARY KEY, correlation_id uuid NOT NULL UNIQUE, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), sku text NOT NULL, quantity integer NOT NULL CHECK(quantity>0), materials_state text DEFAULT 'pending', production_state text DEFAULT 'pending', quality_state text DEFAULT 'pending', attempts integer DEFAULT 0, retry_at timestamptz DEFAULT now(), source text DEFAULT 'synthetic-local');
CREATE TABLE IF NOT EXISTS materials_records(order_id uuid PRIMARY KEY REFERENCES orders, sku text NOT NULL, material_code text NOT NULL DEFAULT 'STEEL-BLANK', quantity integer NOT NULL CHECK(quantity>0), reserved_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS production_records(order_id uuid PRIMARY KEY REFERENCES orders, batch_id uuid NOT NULL UNIQUE, produced_quantity integer NOT NULL CHECK(produced_quantity>0), status text NOT NULL, processed_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_records(order_id uuid PRIMARY KEY REFERENCES orders, inspection_id uuid NOT NULL UNIQUE, expected_units integer NOT NULL, checked_units integer NOT NULL, outcome text NOT NULL CHECK(outcome IN ('pass','hold')), inspected_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS demo_records(worker_id text PRIMARY KEY REFERENCES workers, counter integer DEFAULT 0);
INSERT INTO demo_records(worker_id) SELECT worker_id FROM workers ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS events(seq bigserial PRIMARY KEY,event_id uuid NOT NULL UNIQUE,timestamp timestamptz NOT NULL DEFAULT now(),worker_id text NOT NULL,process_stage text NOT NULL,order_id uuid,correlation_id uuid,operation text NOT NULL,status text NOT NULL CHECK(status IN ('success','error','info')),duration_ms double precision NOT NULL CHECK(duration_ms>=0),error_type text,error_message text,source text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',training_eligible boolean NOT NULL DEFAULT false);
CREATE INDEX IF NOT EXISTS events_worker_time ON events(worker_id,timestamp DESC);
CREATE INDEX IF NOT EXISTS events_correlation ON events(correlation_id);
CREATE TABLE IF NOT EXISTS baselines(worker_id text PRIMARY KEY REFERENCES workers, trained_at timestamptz DEFAULT now(), sample_count integer NOT NULL, training_max_seq bigint NOT NULL, event_ids jsonb NOT NULL, features jsonb NOT NULL, threshold_ms double precision NOT NULL, metadata jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS investigations(id uuid PRIMARY KEY,worker_id text NOT NULL,stage text NOT NULL,started_at timestamptz NOT NULL,last_anomaly_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'open',recovered_at timestamptz,report jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS anomalies(id uuid PRIMARY KEY,event_id uuid NOT NULL UNIQUE REFERENCES events(event_id),worker_id text NOT NULL, timestamp timestamptz NOT NULL,detectors jsonb NOT NULL,ml_score double precision,investigation_id uuid REFERENCES investigations(id));
CREATE TABLE IF NOT EXISTS checkpoints(name text PRIMARY KEY,seq bigint NOT NULL DEFAULT 0);
INSERT INTO checkpoints(name) VALUES ('detector') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS process_snapshots(id bigserial PRIMARY KEY,timestamp timestamptz DEFAULT now(),backlog integer NOT NULL,production_queue integer NOT NULL,quality_queue integer NOT NULL,completed integer NOT NULL);
CREATE INDEX IF NOT EXISTS snapshots_time ON process_snapshots(timestamp DESC);
